### ISSUE TITLE
Positive distance threshold for comparison with Cattaneo's paper

### ISSUE THREAD

**Issue by yunjinli** [alexjunholee/LC2_crossmatching#1]
Hi, 

It was a really nice work that you have done :) Really appreciate! I just have one question regarding the evaluation. In your paper, you compared the performance of your model with Cattaneo's result. What was the distance threshold that you used in this case? Is it 25m as stated in test_pr.py? I look forward to your reply, thanks! 
```
dataset = VisibilityDataset(opt.dataset_root_dir, opt.query_seq, opt.db_seq, transform=input_transform(),
                           bs=int(config['test']['cachebatchsize']), threads=1,
                           margin=0.1, posDistThr=25)
```

**Comment by alexjunholee** [comment]
Hi yunjinli,

As in Cattaneo's experiment, we set 20m as the ground truth positive threshold.
Please change posDistThr=20m to reproduce the result.

And make sure you prepare a database in the 10m interval query and 20m interval database!

"To perform a comparison we followed an evaluation scheme similar to theirs, considering images and point clouds with an interval of 20m (instead of 5m) for the database runs and 10m for the query runs, over the same 43 runs."

Thanks!
Alex

**Comment by yunjinli** [comment]
Hi alexjunholee,

Thanks for your reply! It's very helpful :)

**Comment by yunjinli** [comment]
solved!
